### ISSUE TITLE
acm program

### ISSUE THREAD

**Issue by amitasha** [shiivangii/NLP_Tutorial#1]
hello mam i am student from acm internship program. actually mam i am 2-3 classes behind because of my college online end term exams, mam as i am lagging behind can you please suggest me that when we have to work on the projects and will it be in a group and how groups will be formed? and by when we have to submit the project ? i will try to complete my left over course from recorded sessions. i will be needing some extra time to complete it
 
thankyou

**Comment by ritwikmishra** [comment]
there is no compulsion to make a world-class artificial intelligence model
just go through the videos
think of something in your life where you can implement what you learned through the workshop to solve a real-world problem or to make an interesting analysis on something
